# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6beba9bd96b3df152c07a83ce3ab73e59b54f2dfcfe343fac5e17f9e2cd7fd1fccf3a2112dee2dfaa1f179bbd19815915b23418e2263105546e14dca24e957f

test:
  secret_key_base: 52e529e4fa21d75c41733716c525be93449950bcf912e318e5be27da3d445a60942e6ba1de79c55015350d8fc54f5ff33e825cf9ce0092e535ecfc835d2faefd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
